### ISSUE TITLE
Adding i18n

### ISSUE THREAD

**Issue by fantompocong** [albugowy15/bughowi.com#49]
Hi Mas Owi, I really like your blog structure, I plan to use it as a template for my portfolio site. Do you have any plan to add i18n in this blog? Thanks

**Comment by albugowy15** [comment]
Thanks, that would be great, but for now, I'm focusing to write and deliver all my blog posts only in English

**Comment by fantompocong** [comment]
Looking forward to it. I deployed my site [https://pocong.xyz/](https://pocong.xyz/) already, thanks to you!
